/*:
 On the execution result screen are two graphs showing the input and the output of a Fourier Transform done on a complex tone generated by a piano at A4, or 440Hz
 
 Notice that this complex tone is not only made up of a pure tone at 440 Hz but also other pure tones at 880Hz, 1320Hz…
 
 (Typical Fourier Transform plots use a logarithmic scale, but to show the equidistant relationship between component frequencies, a linear scale is being used here)
 */
//#-hidden-code
import PlaygroundSupport
import UIKit

let mainView = UIView()
let viewController = WaveFormAndFFTViewController()
viewController.mediaType = .file(Constants.Resources.PianoNoteURL)
mainView.addAndCenterSubview(subView: viewController.view, subViewHeight: Constants.ViewHeight.WaveFormAndFFTView, horizontalInset: 30)
mainView.backgroundColor = Constants.Colors.LightGray
PlaygroundPage.current.liveView = mainView
//#-end-hidden-code
